// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"github.com/airdb/uic/internal/app/adapter/repository"
)

// Injectors from wire.go:

// InitializeEvent creates an Event. It will error if the Event is staffed with
// a grumpy greeter.
func InitInjection() repository.OauthConfig {
	oauthConfig := repository.GetOauthConfig()
	return oauthConfig
}

func InitInjectionUser() repository.User {
	user := repository.GetUser()
	return user
}
